### ISSUE TITLE
errant tab in new comment

### ISSUE THREAD

**Issue by iamfromit** [jaichandra/comment-timestamp#1]
I find the inserted "/t" tab at the beginning of each [new comment ](https://github.com/jaichandra/comment-timestamp/blob/master/lib/comment-timestamp.coffee)to be unwanted. Is there a need for it? I believe two things should happen. Remove that tab from the default comment string; add a configurable preamble if necessary or perhaps checkbox configuration items for situations where a tab makes sense before every comment.

**Comment by jaichandra** [comment]
Agree. Its just how I had it for my personal work. I'll make it configurable.

**Comment by jaichandra** [comment]
published new version https://atom.io/packages/comment-timestamp
